In [3]:
# lib import 
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
import numpy as np

2022-01-08 09:43:07.979107: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-01-08 09:43:07.979125: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [4]:
# Loading database and creating previsors 
base = datasets.load_iris()
previsores = base.data
vclass = base.target
vclass

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [5]:
# class to dummy because the neural network have 3 exit layers 
vclass_dummy = np_utils.to_categorical(vclass)
vclass_dummy

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [6]:
# 70/30 split 
X_training, X_test, y_training, y_test = train_test_split(previsores,
                                                                  vclass_dummy,
                                                                  test_size = 0.3,
                                                                  random_state = 0)

In [7]:
# creating neural network with Sequential class 
model = Sequential()
#first hidden layer
model.add(Dense(units = 5, input_dim = 4))
#second hidden layer 
model.add(Dense(units = 4))
# softmax because we have more than 2 vclass
# generate a probability in each neuron
model.add(Dense(units = 3, activation = 'softmax'))

2022-01-08 09:43:10.462385: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2022-01-08 09:43:10.462408: W tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
2022-01-08 09:43:10.462425: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (GUIMS-manjaro): /proc/driver/nvidia/version does not exist
2022-01-08 09:43:10.462585: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [8]:
# neural network structure 
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 5)                 25        
                                                                 
 dense_1 (Dense)             (None, 4)                 24        
                                                                 
 dense_2 (Dense)             (None, 3)                 15        
                                                                 
Total params: 64
Trainable params: 64
Non-trainable params: 0
_________________________________________________________________


In [9]:
# parameter config 
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy',
               metrics = ['accuracy'])
# traning and deviding to validate 
model.fit(X_training, y_training, epochs = 1000,
           validation_data = (X_test, y_test))

Epoch 1/1000
4/4 [==============================] - 0s 36ms/step - loss: 2.5590 - accuracy: 0.3238 - val_loss: 2.1828 - val_accuracy: 0.3556
Epoch 2/1000
4/4 [==============================] - 0s 6ms/step - loss: 2.1874 - accuracy: 0.3238 - val_loss: 1.8886 - val_accuracy: 0.3556
Epoch 3/1000
4/4 [==============================] - 0s 7ms/step - loss: 1.8339 - accuracy: 0.3238 - val_loss: 1.6327 - val_accuracy: 0.3556
Epoch 4/1000
4/4 [==============================] - 0s 6ms/step - loss: 1.5296 - accuracy: 0.3238 - val_loss: 1.4259 - val_accuracy: 0.3556
Epoch 5/1000
4/4 [==============================] - 0s 6ms/step - loss: 1.2967 - accuracy: 0.3238 - val_loss: 1.2807 - val_accuracy: 0.3556
Epoch 6/1000
4/4 [==============================] - 0s 6ms/step - loss: 1.1294 - accuracy: 0.4000 - val_loss: 1.2005 - val_accuracy: 0.5778
Epoch 7/1000
4/4 [==============================] - 0s 6ms/step - loss: 1.0337 - accuracy: 0.6952 - val_loss: 1.1683 - val_accuracy: 0.6000
Epoch 8/1000
4/4 [=

In [10]:
# predicting and changing variable to true and false according to threshold
prediction = model.predict(X_test)
prediction = (prediction > 0.5)
prediction

array([[False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False, False,  True],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [ True, False, False],
       [False, False,  True],
       [ True, False, False],
       [ True, False, False],
       [False,  True, False],
       [False,  True, False],
       [ True, False, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False],
       [Fa

In [11]:
# because it is a 3 exit problem, we need to search the highest number
y_test_matrix = [np.argmax(t) for t in y_test]
y_prediction_matrix = [np.argmax(t) for t in previsoes]

In [12]:
# generating confusion matrix
confusion = confusion_matrix(y_test_matrix, y_prediction_matrix)
confusion

array([[16,  0,  0],
       [ 0, 17,  1],
       [ 0,  0, 11]])